name: Engine update

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mod repository (master)
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run engine-update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tools/engine-update.py
